import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-lato",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased flex`}>
        <aside>
          <Navbar />
        </aside>
        <main className="w-full">
          {children}
        </main>
      </body>
    </html>
  );
}